// Searches Unsplash for a good photo per food/snack/drink item and writes
// src/data/photos.ts as an id -> image URL map.
// Regenerate with: UNSPLASH_ACCESS_KEY=xxx npm run fetch:images
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY
if (!ACCESS_KEY) {
  console.warn(
    'Missing UNSPLASH_ACCESS_KEY — skipping image fetch, leaving src/data/photos.ts untouched.',
  )
  process.exit(0)
}

const QUERIES = {
  'food-1': 'lemon butter pasta',
  'food-2': 'sushi platter',
  'food-3': 'street tacos',
  'food-4': 'cheeseburger',
  'food-5': 'thai noodles',
  'food-6': 'butter chicken naan',
  'food-7': 'wood fired pizza',
  'food-8': 'mushroom risotto',
  'food-9': 'grilled ribeye steak',
  'food-10': 'hummus platter',
  'food-11': 'dumplings plate',
  'food-12': 'french onion soup',

  'snack-1': 'buttered popcorn bowl',
  'snack-2': 'chocolate covered strawberries',
  'snack-3': 'gummy candy',
  'snack-4': 'roasted nuts bowl',
  'snack-5': 'mochi ice cream',
  'snack-6': 'loaded nachos',
  'snack-7': 'mini cheesecake bites',
  'snack-8': 'soft pretzel',
  'snack-9': 'chocolate truffles',
  'snack-10': 'potato chips',

  'drink-1': 'red wine glass',
  'drink-2': 'margarita cocktail',
  'drink-3': 'berry mocktail',
  'drink-4': 'milkshake glass',
  'drink-5': 'old fashioned cocktail',
  'drink-6': 'cola glass ice',
  'drink-7': 'sparkling mocktail glass',
  'drink-8': 'chai tea cup',
  'drink-9': 'craft beer glass',
  'drink-10': 'iced matcha latte',
}

async function searchPhoto(query) {
  const url = new URL('https://api.unsplash.com/search/photos')
  url.searchParams.set('query', query)
  url.searchParams.set('per_page', '1')
  url.searchParams.set('orientation', 'squarish')
  const res = await fetch(url, {
    headers: { Authorization: `Client-ID ${ACCESS_KEY}` },
  })
  if (!res.ok) {
    throw new Error(`Unsplash search failed: ${res.status} ${await res.text()}`)
  }
  const data = await res.json()
  return data.results?.[0]?.urls?.small ?? null
}

async function main() {
  const result = {}

  for (const [id, query] of Object.entries(QUERIES)) {
    try {
      const url = await searchPhoto(query)
      if (url) result[id] = url
      else console.warn(`No result for "${query}" (${id})`)
    } catch (err) {
      console.warn(`Skipping ${id}: ${err.message}`)
    }
    await new Promise((r) => setTimeout(r, 150))
  }

  const outPath = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    '..',
    'src',
    'data',
    'photos.ts',
  )

  const body = `// Generated by scripts/fetch-images.mjs — do not hand-edit.
// Regenerate with: UNSPLASH_ACCESS_KEY=xxx npm run fetch:images
export const photosById: Record<string, string> = ${JSON.stringify(result, null, 2)}
`
  await writeFile(outPath, body)
  console.log(`Wrote ${Object.keys(result).length} photos to ${outPath}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
