// Generated by scripts/fetch-movies.mjs — do not hand-edit.
// Regenerate with: TMDB_API_KEY=xxx npm run fetch:movies
import type { MovieCard } from '../types'

export const movies: MovieCard[] = [
  {
    "id": "movie-tmdb-1202033",
    "kind": "movie",
    "title": "Enola Holmes 3",
    "image": "https://image.tmdb.org/t/p/w500/7kRYHH9H9PjBFwz1FprbHB2AAjI.jpg",
    "genre": [
      "action",
      "thriller"
    ],
    "runtimeMinutes": 109,
    "platform": "Netflix",
    "rating": "PG-13",
    "mood": [
      "spontaneous",
      "scary"
    ],
    "reason": "Trending everywhere right now",
    "synopsis": "Adventure follows detective Enola Holmes to Malta, where her plans to tie the knot unravel when Sherlock's disappearance plunges her into a perilous case.",
    "cast": [
      "Millie Bobby Brown",
      "Henry Cavill",
      "Helena Bonham Carter"
    ]
  },
  {
    "id": "movie-tmdb-687163",
    "kind": "movie",
    "title": "Project Hail Mary",
    "image": "https://image.tmdb.org/t/p/w500/yihdXomYb5kTeSivtFndMy5iDmf.jpg",
    "genre": [
      "sci-fi",
      "action"
    ],
    "runtimeMinutes": 157,
    "platform": "Prime Video",
    "rating": "PG-13",
    "mood": [
      "spontaneous"
    ],
    "reason": "Trending everywhere right now",
    "synopsis": "Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysteriou",
    "cast": [
      "Ryan Gosling",
      "Sandra Hüller",
      "James Ortiz"
    ]
  },
  {
    "id": "movie-tmdb-1301421",
    "kind": "movie",
    "title": "The Sheep Detectives",
    "image": "https://image.tmdb.org/t/p/w500/TEaSqmI6TZQVimULYbingDIdXT.jpg",
    "genre": [
      "comedy",
      "animated",
      "thriller"
    ],
    "runtimeMinutes": 109,
    "platform": "Prime Video",
    "rating": "PG",
    "mood": [
      "funny",
      "cozy",
      "scary"
    ],
    "reason": "Trending everywhere right now",
    "synopsis": "George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must becom",
    "cast": [
      "Hugh Jackman",
      "Nicholas Braun",
      "Nicholas Galitzine"
    ]
  },
  {
    "id": "movie-tmdb-1304313",
    "kind": "movie",
    "title": "Lee Cronin's The Mummy",
    "image": "https://image.tmdb.org/t/p/w500/1q308iixueCU4pFtSYugNOevtNx.jpg",
    "genre": [
      "horror",
      "thriller"
    ],
    "runtimeMinutes": 133,
    "platform": "HBO Max",
    "rating": "R",
    "mood": [
      "scary"
    ],
    "reason": "Trending everywhere right now",
    "synopsis": "The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare",
    "cast": [
      "Jack Reynor",
      "Laia Costa",
      "May Calamawy"
    ]
  },
  {
    "id": "movie-tmdb-1710008",
    "kind": "movie",
    "title": "Nothing to Lose",
    "image": "https://image.tmdb.org/t/p/w500/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg",
    "genre": [
      "drama",
      "action"
    ],
    "runtimeMinutes": 102,
    "platform": "Netflix",
    "rating": "NR",
    "mood": [
      "fancy",
      "nostalgic",
      "spontaneous"
    ],
    "reason": "Trending everywhere right now",
    "synopsis": "She gave everything to become a mother, so when her young son falls ill, Jada will stop at  nothing to find a donor and save him — no matter the cost.",
    "cast": [
      "Nawell Madani",
      "Guillaume Gouix",
      "Nicolas Briançon"
    ]
  },
  {
    "id": "movie-tmdb-1484913",
    "kind": "movie",
    "title": "Ikka",
    "image": "https://image.tmdb.org/t/p/w500/fp5EAKE8nTx402n1fWz55QsuYY9.jpg",
    "genre": [
      "drama",
      "thriller"
    ],
    "runtimeMinutes": 140,
    "platform": "Netflix",
    "rating": "NR",
    "mood": [
      "fancy",
      "nostalgic",
      "spontaneous"
    ],
    "reason": "Trending everywhere right now",
    "synopsis": "With a loved one's life at stake, a celebrated lawyer must defend a man he suspects is guilty — battling his conscience every step of the way.",
    "cast": [
      "Sunny Deol",
      "Akshaye Khanna",
      "Tillotama Shome"
    ]
  },
  {
    "id": "movie-tmdb-1007757",
    "kind": "movie",
    "title": "Swapped",
    "image": "https://image.tmdb.org/t/p/w500/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg",
    "genre": [
      "action",
      "animated",
      "sci-fi"
    ],
    "runtimeMinutes": 102,
    "platform": "Netflix",
    "rating": "PG",
    "mood": [
      "spontaneous",
      "cozy"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one th",
    "cast": [
      "Michael B. Jordan",
      "Juno Temple",
      "Tracy Morgan"
    ]
  },
  {
    "id": "movie-tmdb-424",
    "kind": "movie",
    "title": "Schindler's List",
    "image": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    "genre": [
      "drama"
    ],
    "runtimeMinutes": 195,
    "platform": "Netflix",
    "rating": "R",
    "mood": [
      "fancy",
      "nostalgic"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    "cast": [
      "Liam Neeson",
      "Ben Kingsley",
      "Ralph Fiennes"
    ]
  },
  {
    "id": "movie-tmdb-389",
    "kind": "movie",
    "title": "12 Angry Men",
    "image": "https://image.tmdb.org/t/p/w500/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg",
    "genre": [
      "drama"
    ],
    "runtimeMinutes": 97,
    "platform": "Prime Video",
    "rating": "NR",
    "mood": [
      "fancy",
      "nostalgic"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes",
    "cast": [
      "Martin Balsam",
      "John Fiedler",
      "Lee J. Cobb"
    ]
  },
  {
    "id": "movie-tmdb-1330021",
    "kind": "movie",
    "title": "Remarkably Bright Creatures",
    "image": "https://image.tmdb.org/t/p/w500/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg",
    "genre": [
      "drama",
      "thriller"
    ],
    "runtimeMinutes": 114,
    "platform": "Netflix",
    "rating": "PG-13",
    "mood": [
      "fancy",
      "nostalgic",
      "scary"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.",
    "cast": [
      "Sally Field",
      "Lewis Pullman",
      "Colm Meaney"
    ]
  },
  {
    "id": "movie-tmdb-129",
    "kind": "movie",
    "title": "Spirited Away",
    "image": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    "genre": [
      "animated",
      "sci-fi"
    ],
    "runtimeMinutes": 125,
    "platform": "HBO Max",
    "rating": "PG",
    "mood": [
      "cozy",
      "spontaneous"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    "cast": [
      "Rumi Hiiragi",
      "Miyu Irino",
      "Mari Natsuki"
    ]
  },
  {
    "id": "movie-tmdb-155",
    "kind": "movie",
    "title": "The Dark Knight",
    "image": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "genre": [
      "action",
      "thriller"
    ],
    "runtimeMinutes": 152,
    "platform": "HBO Max",
    "rating": "PG-13",
    "mood": [
      "spontaneous",
      "scary"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership ",
    "cast": [
      "Christian Bale",
      "Heath Ledger",
      "Aaron Eckhart"
    ]
  },
  {
    "id": "movie-tmdb-19404",
    "kind": "movie",
    "title": "Dilwale Dulhania Le Jayenge",
    "image": "https://image.tmdb.org/t/p/w500/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg",
    "genre": [
      "comedy",
      "drama",
      "romance"
    ],
    "runtimeMinutes": 190,
    "platform": "Netflix",
    "rating": "G",
    "mood": [
      "funny",
      "fancy",
      "nostalgic"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to ",
    "cast": [
      "Kajol",
      "Shah Rukh Khan",
      "Amrish Puri"
    ]
  },
  {
    "id": "movie-tmdb-122",
    "kind": "movie",
    "title": "The Lord of the Rings: The Return of the King",
    "image": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "genre": [
      "action",
      "sci-fi"
    ],
    "runtimeMinutes": 201,
    "platform": "HBO Max",
    "rating": "PG-13",
    "mood": [
      "spontaneous"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble",
    "cast": [
      "Elijah Wood",
      "Ian McKellen",
      "Viggo Mortensen"
    ]
  },
  {
    "id": "movie-tmdb-372058",
    "kind": "movie",
    "title": "Your Name.",
    "image": "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    "genre": [
      "animated",
      "romance",
      "drama"
    ],
    "runtimeMinutes": 106,
    "platform": "HBO Max",
    "rating": "PG",
    "mood": [
      "cozy",
      "romantic",
      "fancy"
    ],
    "reason": "One of the best-reviewed picks available",
    "synopsis": "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen rando",
    "cast": [
      "Ryunosuke Kamiki",
      "Mone Kamishiraishi",
      "Ryo Narita"
    ]
  }
]
